#feign:
#  sentinel:
#    enabled: true
#  okhttp:
#    enabled: true
#  httpclient:
#    enabled: false
#  client:
#    config:
#      default:
#        ## 针对每个服务设置超时时间，这个配置可以覆盖掉ribbon的超时时间
#        connect-timeout: 2000
#        read-timeout: 60000
#      compression:
#        request:
#          enabled: true
#        response:
#          enabled: true