server:
  servlet:
    context-path: /
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 10000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      expireAfterWriteInMills: 86400000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      uri: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}/7
      expireAfterWriteInMills: 86400000
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
spring:
  main:
    allow-circular-references: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: yeah
    database: 0
