server:
  servlet:
    context-path: /
jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 10000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      expireAfterWriteInMills: 86400000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      uri: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}/7
      expireAfterWriteInMills: 86400000
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
#jetcache.statIntervalMinutes=1
#jetcache.areaInCacheName=false
#jetcache.local.default.type=caffeine
#jetcache.local.default.limit=10000
#jetcache.local.default.keyConvertor=fastjson
#jetcache.local.default.valueEncoder=kryo
#jetcache.local.default.valueDecoder=kryo
#jetcache.local.default.expireAfterWriteInMills=86400000
#jetcache.remote.default.type=redis.lettuce
#jetcache.remote.default.keyConvertor=fastjson
#jetcache.remote.default.valueEncoder=kryo
#jetcache.remote.default.valueDecoder=kryo
#jetcache.remote.default.uri=redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}/${spring.redis.database}
#jetcache.remote.default.expireAfterWriteInMills=86400000
#jetcache.remote.default.poolConfig.minIdle=5
#jetcache.remote.default.poolConfig.maxIdle=20
#jetcache.remote.default.poolConfig.maxTotal=50
spring:
  main:
    allow-circular-references: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: yeah
    database: 0
