server:
  port: 8808
  servlet:
    context-path: /auth-server
logging:
  level:
    org:
      springframework:
        security: debug
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: cloud-web-auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yeee_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: e69ceae8-160c-4d52-b512-ad0e919ad86b
        group: ${spring.profiles.active}
        metadata:
          api-version: ${yeee.api-version}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
yeee:
  api-version: 2.0
  swagger:
    enable: true
    title: 认证授权中心
    description: 认证授权中心
    contact-name: yeee
    version: 1.0
  auth:
    jwt-secret: 123456
    server:
    resource:
      exclude:
        - "/front/register"
        - "/system/register"
        - "/front/login"
        - "/system/login"
        - "/anonymous/limit/api"