spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: cloud-web-auth-server-2.0
          uri: lb://cloud-web-auth-server
          predicates:
            - Path=/v20/auth-server/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=api-version,2.0