server:
  port: 8808
  servlet:
    context-path: /auth-server
logging:
  level:
    org:
      springframework:
        security: debug
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: cloud-web-auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yeee_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: e69ceae8-160c-4d52-b512-ad0e919ad86b
        group: ${spring.profiles.active}
security:
  oauth2:
    resource:
      token-info-uri: http://${spring.application.name}/auth-server/oauth/check_token
    client:
      client-id: user-auth-center
      client-secret: 123456
#      grant-type: password
      access-token-uri: http://${spring.application.name}/auth-server/oauth/token
auth:
  server:
    jwt-secret: test_key
  resource:
    exclude:
      - /error
      - /actuator/info
      - /front/register
      - /system/register
      - /front/login
      - /system/login
      - /anonymous/limit/api