server:
  port: 8809
  servlet:
    context-path: /auth-resource1
logging:
  level:
    org:
      springframework:
        security: debug
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: cloud-web-auth-resource1
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: e69ceae8-160c-4d52-b512-ad0e919ad86b
        group: ${spring.profiles.active}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
security:
  oauth2:
    resource:
      token-info-uri: http://cloud-web-auth-server/auth-server/oauth/check_token
    client:
      client-id: ${spring.application.name}
      client-secret: 123456
yeee:
  swagger:
    enable: true
    title: 资源1服务中心
    description: 资源1服务中心
    contact-name: yeee
    version: 1.0
  auth:
    resource:
      exclude:
        - "/"
        - "/doc.html"
        - "/swagger-resources/**"
        - "/swagger/**"
        - "/**/v2/api-docs"
        - "/**/*.js"
        - "/**/*.css"
        - "/**/*.png"
        - "/**/*.jpg"
        - "/**/*.ico"
        - "/**/*.html"
        - "/webjars/springfox-swagger-ui/**"
        - "/actuator/**"
        - "/error"
        - "/anonymous/limit/api"