spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_memo?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    password: root
    username: root
yeee:
  mybatis:
    encrypt:
      password: 1870577f29b17d6787782f35998c4a79