spring:
  kafka:
    bootstrap-servers: yeee.vip.host:21661
    consumer:
      group-id: GID_yeee-memo
      enable-auto-commit: false # 需要ack.acknowledge()
      isolation-level: read_committed
    producer:
      retries: 3
      acks: 1
      transaction-id-prefix: tx_
    listener:
      ack-mode: manual