spring:
  kafka:
    bootstrap-servers: yeee.vip.host:21661
    consumer:
      group-id: GID_yeee-memo
      enable-auto-commit: false
    producer:
      transaction-id-prefix: tx_
    listener:
      ack-mode: manual