package ${package};

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotNull;

/**
 * Generated by Yeeee.一页
 * @since ${generateDate}
 */
@Data
public class ${tableClass.shortClassName}ListRequest {

    @ApiModelProperty("当前页码")
    @NotNull(message = "当前页码不能为空")
    private Integer pageNum;

    @ApiModelProperty("分页大小")
    @NotNull(message = "分页大小不能为空")
    private Integer pageSize;

}