server:
  port: 8810
  servlet:
    context-path: /resource-server2
logging:
  level:
    org:
      springframework:
        security: debug
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: cloud-web-resource-server2
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: e69ceae8-160c-4d52-b512-ad0e919ad86b
        group: ${spring.profiles.active}
        metadata:
          api-version: ${yeee.api-version}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
security:
  oauth2:
    resource:
      token-info-uri: http://cloud-web-auth-server/auth-server/oauth/check_token
    client:
      client-id: ${spring.application.name}
      client-secret: 123456
yeee:
  api-version: 2.0
  swagger:
    enable: true
    title: 资源1服务中心
    description: 资源1服务中心
    contact-name: yeee
    version: 1.0
  auth:
    resource:
      exclude:
        - "/anonymous/limit/api"