spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: yeah
    database: 6
wx:
  ma:
    use-redis: true
    redis-config:
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}
      timeout: 10000
    configs:
      - appId: wxc84b896c35f157b1
        secret: c93ddae2c45d3d5a6a514c03e1dfd73f
        token: yeeee-token
        lessee-id: 1111
        app-type: 10