#security:
#  oauth2:
#    resource:
#      token-info-uri: http://cloud-web-auth-server/auth-server/oauth/check_token
#    client:
#      client-id: ${spring.application.name}
#      client-secret: 123456
#      #      grant-type: password
#      access-token-uri: http://cloud-web-auth-server/auth-server/oauth/token