server:
  servlet:
    context-path: /ffs
  port: 9080
spring:
  profiles:
    active: test
  application:
    name: feign-fallback-sentinel
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: e69ceae8-160c-4d52-b512-ad0e919ad86b
        group: ${spring.profiles.active}
    sentinel:
      transport:
        dashboard: 127.0.0.1:8844
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  client:
    config:
      default:
        ## 针对每个服务设置超时时间，这个配置可以覆盖掉ribbon的超时时间
        connect-timeout: 2000
        read-timeout: 60000