server:
  port: 8082
  servlet:
    context-path: /pay
spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeeee_pay?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
yeee:
  pay:
    site-url: http://127.0.0.1:8082/pay
    notify-url: http://127.0.0.1:8082/pay/notify/%s
    return-url: http://127.0.0.1:8082/pay/return/%s
    refund-notify-url: http://127.0.0.1:8082/pay/return/%s