package ${package};

import ${tableClass.packageName}.${tableClass.shortClassName};
import tk.mybatis.mapper.common.Mapper;

import java.util.List;

/**
 * Generated by Yeeee.一页
 * @since ${generateDate}
 */
public interface ${tableClass.shortClassName}Mapper extends Mapper<${tableClass.shortClassName}> {

    List<${tableClass.shortClassName}> getList(${tableClass.shortClassName} ${tableClass.variableName});

    ${tableClass.shortClassName} getOne(${tableClass.shortClassName} ${tableClass.variableName});

    int batchInsert(List<${tableClass.shortClassName}> ${tableClass.variableName}List);

}